<?php

namespace Buqiu\Cas\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class ClientTicket extends Model
{
    protected $table = 'cas_client_tickets';
    protected $fillable = ['uuid', 'user_id', 'session_id', 'client_token', 'created_at'];
    protected $casts = [
        'created_at' => 'datetime',
    ];
    public $timestamps = false;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            if ( ! $model->uuid) {
                $model->uuid = Str::uuid();
            }
        });
    }

    public function user()
    {
        return $this->belongsTo(config('cas.user_table.model'), 'user_id', config('cas.user_table.id'));
    }
}
